version: "2"
volumes:
  pgdata:
  cache:
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - postgres_conn
    ports:
     - "5432"
    env_file: .env
  import-osm:
    image: "openmaptiles/import-osm:0.5"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./data:/mapping
     - cache:/cache
  generate-sql:
    build: "./generate-sql"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/sql:/sql
      - ./data/stylesheets:/stylesheets
  generate-vodak-sql:
    build: "./generate-vodak-sql"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/sql:/sql
  generate-cartocss:
    build: "./generate-cartocss"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/pattern:/pattern
      - ./build/shield:/shield
      - ./build/symbol:/symbol
      - ./build/cartocss:/cartocss
      - ./data/stylesheets:/stylesheets
  import-sql:
    build: "./import-sql"
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - ./build/sql:/sql
  generate-osmcsymbols:
    build: "./generate-osmcsymbols"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/osmcsymbol:/build
      - ./data/osmcsymbol:/osmcsymbol
  generate-highway-access:
    build: "./generate-highway-access"
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/highway-access:/build
      - ./data/highway-access:/highway_access
  relations2lines:
    build: "./relations2lines"
    env_file: .env
    networks:
      - postgres_conn
networks:
  postgres_conn:
    driver: bridge
