version: "2"
volumes:
  pgdata:
  cache:
services:
  postgres:
    image: "openmaptiles/postgis:2.9"
    volumes:
    - pgdata:/var/lib/postgresql/data
    networks:
    - postgres_conn
    ports:
     - "5432"
    env_file: .env
  import-osm:
    image: "openmaptiles/import-osm:0.5"
    env_file: .env
    environment:
      DIFF_MODE: ${DIFF_MODE}
    networks:
    - postgres_conn
    volumes:
     - ./data:/import
     - ./data:/mapping
     - cache:/cache
  generate-sql:
    build: "./generate-sql"
    image: map1/generate-sql
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/sql:/sql
      - ./data/stylesheets:/stylesheets
  generate-vodak-sql:
    build: "./generate-vodak-sql"
    image: map1/generate-vodak-sql
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/sql:/sql
  generate-cartocss:
    build: "./generate-cartocss"
    image: map1/generate-cartocss
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/pattern:/pattern
      - ./build/shield:/shield
      - ./build/symbol:/symbol
      - ./build/cartocss:/cartocss
      - ./data/stylesheets:/stylesheets
  compile-cartocss:
    build: "./compile-cartocss"
    image: map1/compile-cartocss
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/mapnik-styles:/mapnik-styles
      - ./build/cartocss:/cartocss
  import-sql:
    build: "./import-sql"
    image: map1/import-sql
    env_file: .env
    networks:
    - postgres_conn
    volumes:
     - ./build/sql:/sql
  import-dem:
    build: "./import-dem"
    image: map1/import-dem
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./data/dem:/dem
      - ./build/sql:/sql
      - ./build/hillshade:/hillshade
  generate-osmcsymbols:
    build: "./generate-osmcsymbols"
    image: map1/generate-osmcsymbols
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/osmcsymbol:/build
      - ./data/osmcsymbol:/osmcsymbol
  generate-highway-access:
    build: "./generate-highway-access"
    image: map1/generate-highway-access
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./build/highway-access:/build
      - ./data/highway-access:/highway_access
  relations2lines:
    build: "./relations2lines"
    image: map1/relations2lines
    env_file: .env
    networks:
      - postgres_conn
  render-map:
    build: "./render-map"
    image: map1/render-map
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./data/shp:/shp
      - ./data/fonts:/fonts
      - ./build/pattern:/pattern
      - ./build/shield:/shield
      - ./build/symbol:/symbol
      - ./build/osmcsymbol:/osmcsymbol
      - ./build/highway-access:/highway-access
      - ./build/mapnik-styles:/mapnik-styles
      - ./build/render:/render
  jupyter:
    build: "./jupyter"
    image: map1/jupyter
    depends_on:
      - render-map
    env_file: .env
    networks:
      - postgres_conn
    volumes:
      - ./data/shp:/shp
      - ./data/fonts:/fonts
      - ./build/pattern:/pattern
      - ./build/shield:/shield
      - ./build/symbol:/symbol
      - ./build/osmcsymbol:/osmcsymbol
      - ./build/highway-access:/highway-access
      - ./build/dem:/dem
      - ./build/mapnik-styles:/mapnik-styles
      - ./build/render:/render
      - ./jupyter-notebooks:/notebooks
networks:
  postgres_conn:
    driver: bridge
